package header

const INDEX_OF_DOMAIN_MAIL int = 0     // INDEX OF DOMAIN MAIL IN .config.txt IF IT IS CONFIGURE
const INDEX_OF_SENDER_EMAIL int = 1    // INDEX OF SENDER EMAIL IN .config.txt IF IT IS CONFIGURE
const INDEX_OF_SENDER_PASSWORD int = 2 // INDEX OF THE PASSWORD OF THE SENDER IN .config.txt IF IT IS CONFIGURE
